/**
 * gmLogger.idl
 *
 * Reverse engineered interface gmILogger
 */

#include "nsISupports.idl"

[scriptable, uuid(07d9b512-8e83-418a-a540-0ec804b82195)]
interface gmILogger : nsISupports {
  void log(in AUTF8String aMsg);
};
